### ISSUE TITLE
Crashes when loading NSmnData and NSpnData

### ISSUE THREAD

**Issue by ghost** [Pumbaa98/OnexExplorer#27]
@Pumbaa98 

In the current version 0.6.1 Beta, the tool crashes when I want to open the files NSmnData.nos and NSpnData.nos. Instead of crashing, it would be useful to inform the user that these files are not supported.

**Workaround suggestion:**

**Summary:**
As soon as a user tries to load the file _NSmnData.nos_ or _NSpnData.nos_, a message box (or similar GUI) informs the user that there is currently no support for these two files.

**Implementation suggestion:**
The QFileDialog mentioned in _Source/MainWindow.cpp, line 117_ starts an algorithm which checks the input filename, e. g.:  
```// MainWindow.h  
// ...  
private:  
    // ...  
    bool isFileUnsupported(const QString& filename);  
// ...  
// MainWindow
bool MainWindow::isFileUnsupported(const QString& filename)  
{  
    static const QString unsupportedFilesPattern = "(nsmndata)|(nspndata)";   
    QRegExp regExp(unsupportedFilesPattern);  
    regExp.setCaseSensitivity(Qt::CaseSensitivity::CaseInsensitive);  
    return !regex.indexIn(filename) < 0;  
}
```

**Acceptance criteria:**
- The software won't crash anymore
- The user gets informed about the support issue
- The user can continue operating with the software

**Comment by Pumba98** [comment]
Thanks, i was aware of the issue.
There would be an easier way to solve this in hasValidHeader function.
Anyway the nsmn/pn will be added in the next version so this is obsolete.
Implementation already started https://github.com/Pumbaa98/OnexExplorer/tree/feature/ccinf
